name: Main manual pipeline

on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Package version'
        required: true
        default: 3.0.0
        type: number
      ReleaseNum:
        description: 'Release Num'
        required: true
        default: 1
        type: number
      Architecture:
        description: 'Architecture'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - arm64
        - amd64
      Depends:
        description: 'Dependencies'
        required: true
        default: 'astemo-variant (= 3.0.0),
          qnx-sdp (= 3.0.0),
          qcom-amss (= 3.0.0),
          astemo-tools (= 3.0.0),
          qcom-qnx (= 3.0.0),
          qcom-license (= 3.0.0),
          libssl1.0-dev,
          cmake (>= 3.17.1),
          device-tree-compiler (>= 1.4.4),
          fastboot,
          filepp (>= 1.8.0),
          swig (>= 3.0.12),
          bison (>= 3.0.4),
          flex,
          git (>= 2.17.0),
          python2.7,
          python2.7-dev,
          python3 (>= 3.9.17),
          python3-pip,
          python3-distutils,
          dotnet-sdk-7.0,
          iasl,
          gcc,
          liblocal-lib-perl,
          cpanminus,
          libxml-simple-perl,
          build-essential,
          uuid-dev,
          libncurses5,
          software-properties-common,
          apt-transport-https,
          wget,
          curl'
        type: string

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
